// File generated by FlutterFire CLI.
// This file contains dummy Firebase options for testing purposes.
// In a real app, you should use flutterfire configure to generate this file.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// This is a dummy implementation for testing purposes.
/// In production, use flutterfire configure to generate this file.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqor12665z7H5r70DtoIowGhOx5GMNYDs',
    appId: '1:525304577839:web:f574e425064c31cbc02bda',
    messagingSenderId: '525304577839',
    projectId: 'tiju-s-elearn',
    authDomain: 'tiju-s-elearn.firebaseapp.com',
    storageBucket: 'tiju-s-elearn.firebasestorage.app',
    measurementId: 'G-EH8K0RGT08',
  );

  // Dummy Firebase options for Web

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaUaup5BWnlaURDpGPpZSUHO7buBlrOAM',
    appId: '1:525304577839:android:88622c9c7a0c1695c02bda',
    messagingSenderId: '525304577839',
    projectId: 'tiju-s-elearn',
    storageBucket: 'tiju-s-elearn.firebasestorage.app',
  );

  // Dummy Firebase options for Android

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq7zbFU6HxZNqT7fw9iEGTQXodubfu8AM',
    appId: '1:525304577839:ios:2993157705b64108c02bda',
    messagingSenderId: '525304577839',
    projectId: 'tiju-s-elearn',
    storageBucket: 'tiju-s-elearn.firebasestorage.app',
    iosBundleId: 'com.example.tijusAcademy',
  );

  // Dummy Firebase options for iOS

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq7zbFU6HxZNqT7fw9iEGTQXodubfu8AM',
    appId: '1:525304577839:ios:2993157705b64108c02bda',
    messagingSenderId: '525304577839',
    projectId: 'tiju-s-elearn',
    storageBucket: 'tiju-s-elearn.firebasestorage.app',
    iosBundleId: 'com.example.tijusAcademy',
  );

  // Dummy Firebase options for macOS

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqor12665z7H5r70DtoIowGhOx5GMNYDs',
    appId: '1:525304577839:web:92c042fd478112fac02bda',
    messagingSenderId: '525304577839',
    projectId: 'tiju-s-elearn',
    authDomain: 'tiju-s-elearn.firebaseapp.com',
    storageBucket: 'tiju-s-elearn.firebasestorage.app',
    measurementId: 'G-N8VLECZKN5',
  );

  // Dummy Firebase options for Windows

  // Dummy Firebase options for Linux
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'dummy-api-key',
    appId: '1:1234567890:linux:abcdef1234567890',
    messagingSenderId: '1234567890',
    projectId: 'dummy-project-id',
    storageBucket: 'dummy-project-id.appspot.com',
  );
}
